version: '3.7'
services:
  app:
    depends_on:
      - database
    build: .
    environment:
      NODE_ENV: stage
      INTERNAL_SECRET: 123
      DATABASE_SSL: "false"
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 123
      PORT: 8080
    #image: jibrelnetwork/jibrel-com-web:latest
    ports:
      - "80:8080"
    restart: always

  database:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
